### PR TITLE
Fixes changing the canceled promises' state bug

### LINKED ISSUE #33: isCanceled is not set to true when shouldReject is set to false and promise is rejected in onCancel
I'm doing some `p-cancelable` testing to get familiar with it and I noticed that `isCanceled` is not set to `true` on the promise when the promise is canceled with `shouldReject` set to `false`. 

I briefly took a look at the library code but TBH I don't see any reason for this to happen so reporting this issue.

My code is (I know, ugly but as said it is my test code):

```js
import PCancelable from 'p-cancelable';

const cancelablePromise = doJob();

try {
    await sleep(500);

    cancelablePromise.cancel();
}
catch (error) {
    console.log("First main catch error: " + error);
}

try {
    const result = await cancelablePromise;
    console.log("result", result);
} catch (error) {
    console.log("Second main catch error: " + error);

    if (cancelablePromise.isCanceled)
        console.log("Don't worry it was canceled")
}

function sleep(ms) {
    return new Promise((resolve) => {
        setTimeout(resolve, ms);
    });
}

function doJob() {
    return new PCancelable((resolve, reject, onCancel) => {
        try {
            const timeout = setTimeout(() => {
                const result = job();
                resolve(result);
            }, 1000);

            onCancel.shouldReject = false;

            onCancel(() => {
                console.log('canceled');
                clearTimeout(timeout);
                reject(new Error('canceled'));
            });
        }
        catch (error) {
            console.log('Promise catch error: ' + error);
            reject(error);
        }
    });
}
```

## Current behavior:
```
> node .\index.js
canceled
Second main catch error: Error: canceled
```

## Expected behavior:
```
> node .\index.js
canceled
Second main catch error: CancelError: Promise was canceled
Don't worry it was canceled
```

If I remove `onCancel.shouldReject = false;` then it is fine.

### PR DESCRIPTION
**Pull request by jopemachine**
Fix #33.

This PR fixes a bug changing the canceled promises' state.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -37,14 +37,20 @@ export default class PCancelable {
 			const onResolve = value => {
 				if (this.#state !== promiseState.canceled || !onCancel.shouldReject) {
 					resolve(value);
-					this.#state = promiseState.resolved;
+
+					if (this.#state !== promiseState.canceled) {
+						this.#state = promiseState.resolved;
+					}
```
Comment (sindresorhus) [inline index.js:43]: Let's do an internal `.setState()` method that only sets the state if it's `pending`. And then use it everywhere `this.#state =` is used.
